# Generated by Django 4.2.4 on 2023-09-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('huesped', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacion')),
            ],
        ),
    ]
