# Generated by Django 4.2.4 on 2023-09-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_huesped_habitacion_remove_huesped_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huespedxhabitacion',
            old_name='habitacion',
            new_name='habitacion_rel',
        ),
        migrations.RenameField(
            model_name='huespedxhabitacion',
            old_name='huesped',
            new_name='huesped_rel',
        ),
    ]
