# Generated by Django 4.2.4 on 2023-10-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_habitacion_huespedxhabitacion_habitacion_rel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huespedxhabitacion',
            name='salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
