# Generated by Django 4.2.4 on 2023-10-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_huespedxhabitacion_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='huespedxhabitacion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
