# Generated by Django 4.2.4 on 2023-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_huespedxhabitacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
